package Models;
// Generated Jul 30, 2022 12:38:56 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * BookUsers generated by hbm2java
 */
public class BookUsers  implements java.io.Serializable {


     private Integer id;
     private int bookId;
     private int userId;
     private Date createdAt;

    public BookUsers() {
    }

    public BookUsers(int bookId, int userId, Date createdAt) {
       this.bookId = bookId;
       this.userId = userId;
       this.createdAt = createdAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }


    public static Serializable save(BookUsers book_user){  
        Session session = util.HibernateUtil.getSessionFactory().openSession();
        Transaction transaction = session.beginTransaction();
        Serializable status;
        try {
            status = session.save(book_user);
            transaction.commit();
            session.close();
        } catch (Exception e) {
            status = null;
        }
        return status;
    }

}


